# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c95ae261875abe745ab3cf237a35e3a0cc1cfc245d1a1677d49fe78025a9852fc88915aa4153b4eb4b03f754f1a4e404fac0e37ecb75db2cd35d5bebcd9550f

test:
  secret_key_base: 700a9bb9778db8d0024ac78019c3f7f6768b670e1f56493b43e36eaf9c81ba597af9b1ee8c4844bff09ac1381cbd66a3c8bd7cb16258331aa9b831926360a3d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
